spring:
  cloud:
    gateway:
      routes:
        - id: example-service
          uri: http://localhost:8080
          predicates:
            - Path=/actiontype/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin